baseURL: "/"
title: Sayfullah Sayeb
pagination.pagerSize: 10
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Sayfullah Sayeb
  description: "Md Sayfullah Sayeb - Co-founder of Labartise and a Bangladeshi web developer. Specializes in web-based solutions, game mods, and mobile apps. Learn more on his website."
  keywords: [Blog, Portfolio, Sayfullah, Sayeb, Sayfullah Sayeb]
  author: Sayfullah Sayeb
  # author: ["Me", "You"] # multiple authors
  images: ["sayfullah-cover.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: true
  ShowReadingTime: true
#  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
#  disableSpecial1stPost: false
  disableScrollToTop: false
#  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  mainSections: []
  ShowAllPagesInArchive: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
#    favicon16x16: "/favicon-16x16.png"
#    favicon32x32: "/favicon-32x32.png"
#    apple_touch_icon: "/apple-touch-icon.png"
#    safari_pinned_tab: "/safari-pinned-tab.svg"

  label:
    text: "Sayfullah Sayeb"
#    icon: /apple-touch-icon.png
#   iconHeight: 35

  # # profile-mode
  # profileMode:
  #   enabled: false # needs to be explicitly set
  #   title: ExampleSite
  #   subtitle: "This is subtitle"
  #   imageUrl: "<img location>"
  #   imageWidth: 120
  #   imageHeight: 120
  #   imageTitle: my image
  #   buttons:
  #     - name: Posts
  #       url: posts
  #     - name: Tags
  #       url: tags


  homeInfoParams:
    Title: "As-salamu alaykum,"
    Content: |
      I'm **Md Sayfullah Sayeb**, but you can call me **Sayeb** or **সাইব** `(Bangla)`. I was born and still reside in Bangladesh. I'm currently the Co-founder of <a href="https://labartise.com/" target="_blank" style="color: #f5a97f;"><strong>Labartise</strong></a>, an Indian startup specializing in web-based operations.

      I'm a passionate web developer and tech enthusiast who loves solving web-based problems, building websites, creating mods for games, and making mobile apps.

      Outside of work, I enjoy reading, playing video games, and listening to music and audiobooks. I'm interested in privacy, security, and translations, and I also enjoy slow walks on summer nights. Plus, I laugh at my own jokes!

      Just because something is my interest doesn't mean that I must be particularly good at it. Over the years, I've worked on exciting projects and learned new technologies, which you can find on my <a href="https://github.com/mdsayeb7?tab=repositories" target="_blank" rel="noopener noreferrer" style="color: #f5a97f;"><strong>GitHub</strong></a>. I'm still continuing to learn. 

      <p>To know more about me, feel free to check out my <a href="https://drive.google.com/file/d/1xilpbq_LcxujTlxPRLge8lSuIlGYtC0M/view" style="color: #f5a97f;" target="_blank"><strong>Resume</strong></a>. Additionally, here's a directory of my socials:


      - <a href="https://github.com/mdsayeb7" target="_blank"   style="color: #f5a97f;"><strong>GitHub</strong></a>   (`mdsayeb7`)
      - <a href="https://t.me/sayeb7" target="_blank"  style="color: #f5a97f;"><strong>Telegram</strong></a>  (`@sayeb7`)
      - <a href="https://t.me/sayfullahsayeb" target="_blank" style="color: #f5a97f;"><strong>Telegram Channel</strong></a> (`@sayfullahsayeb`)
      - <a href="https://www.linkedin.com/in/sayfullahsayeb/" target="_blank" style="color: #f5a97f;  "><strong>LinkedIn</strong></a> (`sayfullahsayeb`)
      - <a href="mailto:sayfullah.sayeb@gmail.com"      target="_blank" style="color: #f5a97f;"><strong>Email</strong></a> (`sayfullah.sayeb@gmail.com`)
      - <a href="/index.xml" target="_blank" style="color: #f5a97f;"><strong>RSS Feed</strong></a> (`index.xml`)

      <br>

      This <a href="/posts" style="color: #f5a97f;"><strong>blog</strong></a> is mainly for sharing niche or specific information I've found worth archiving. It's about my hard- and software projects, server administration, and other related topics. Occasionally, I might write about my life too.



#  socialIcons:
#      url: "https://example.com"
#    - name: github
#      url: "https://github.com/mdsayeb7"
#    - name: linkedin
#      url: "https://www.linkedin.com/in/sayfullahsayeb/"
#    - name: email
#      url: "mailto:sayfullah.sayeb@gmail.com"
#    - name: telegram
#      url: "https://t.me/SayebPD"

  analytics:
    google:
      SiteVerificationTag: "G-NFMHC0M93N"
#    bing:
#      SiteVerificationTag: ""
#    yandex:
#      SiteVerificationTag: ""

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

#  editPost:
#    URL: "https://github.com/<path_to_repo>/content"
#    Text: "Suggest Changes" # edit text
#    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - name: Main Page
      url: /
      weight: 1
    - name: Posts
      url: /posts/
      weight: 5
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: photography
      name: Photography
      url: /photography/
      weight: 15
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - name: Search
      url: /search/
      weight: 25

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
markup:
    goldmark:
        renderer:
            unsafe: true
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai
#languages:
#  en:
#    languageName: "English"
#    weight: 1
#  bn:
#    languageName: "বাংলা"
#    weight: 2
outputs:
    home:
        - HTML
        - RSS
        - JSON
